# Setup
name: 地球商店
description: '来自平行宇宙的奇物脑洞站'
url: https://Yuilit.github.io # 需要在添加SSL证书后修改为 https
baseurl: ''
permalink:           pretty
#github:              https://github.com
#twitter:             https://twitter.com
rss:                 /atom.xml
deploy:              Cloudflare

# About/contact
author:
  name:              earthshop
  url:               https://earthshop.com
  email:             xxxx@xx.com


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "generate-tag-pages.bat", "generate-tag-pages.sh"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    default_lang: text
    css: style
    span:
      line_numbers: false
    block:
      line_numbers: false
